Debugged latest approach

diff --git a/support/drunner b/support/drunner
--- a/support/drunner
+++ b/support/drunner
@@ -27,6 +27,8 @@ readonly MYDIR=$( dirname "$(readlink -f "$0")" )
 if ! "${MYDIR}/validator-drunner" ; then exit 1 ; fi
 
 source "/etc/drunner/config.sh"
+[ -d ${ROOTPATH} ] || { echo "Installation broken. Please run drunner-install again.">&2 ; exit 1 ; }
+
 source "${ROOTPATH}/support/buildtime.sh"
 source "${ROOTPATH}/support/drunner-util-functions.sh"
 source "${ROOTPATH}/support/drunner-install-service.sh"
@@ -81,6 +83,7 @@ SYNOPSIS
    drunner recover SERVICENAME
    drunner destroy SERVICENAME
    drunner enter   SERVICENAME [ARGS]
+   drunner status  SERVICENAME
    
    SERVICENAME
    SERVICENAME COMMAND ARGS
@@ -256,6 +259,15 @@ function processdRunnerCommands {
          fi
          SERVICENAME="$3"
          restore "$2"
+         exit 0
+         ;;
+         
+      status) 
+         [ "$#" -eq 2 ] || dieusage "drunner status SERVICENAME"
+         SERVICENAME="$2"
+         [ -e "${ROOTPATH}/services/${SERVICENAME}" ] || die "${SERVICENAME} is not installed. If you need to recover, install it and any existing Docker volumes will be preserved."
+         "${ROOTPATH}/support/validator-service" "$SERVICENAME" || die "Validation failed!"
+         echo "${SERVICENAME} is installed and okay."
          exit 0
          ;;
          
diff --git a/support/validator-service b/support/validator-service
--- a/support/validator-service
+++ b/support/validator-service
@@ -22,9 +22,9 @@ function die {
    
    [ -z "$NUKEOK" ] || exit 1
       
-   echo -e "You can try moving the folder aside (${ROOTPATH}/services/${SERVICENAME})">&2
-   echo -e "then installing with the same SERVICENAME and IMAGENAME. Data and configuration">&2
-   echo -e "should be preserved if you're coming from a stable release.">&2
+   echo -e " ">&2
+   echo -e "You can try recovering with ${CODE_S}drunner recover ${SERVICENAME}${CODE_E}.">&2
+   echo -e "That will preserve data and configuration and should be safe to try.">&2
    echo -e " ">&2
    exit 1
 }
@@ -54,7 +54,7 @@ for CFILE in "${REQDFILES[@]}"; do
    [ -e "${ROOTPATH}/services/${SERVICENAME}/$CFILE" ] || die "Required file not present: $CFILE"
 done
 
-readonly SOURCEFILES=("imagename.sh" "drunner/servicecfg.sh" "drunner/variables.sh")
+readonly SOURCEFILES=("imagename.sh" "drunner/servicecfg.sh" "drunner/variables.sh" "drunner/utils.sh")
 for CFILE in "${SOURCEFILES[@]}"; do
    [ -e "${ROOTPATH}/services/${SERVICENAME}/$CFILE" ] || die "Required file not present: $CFILE"
    source "${ROOTPATH}/services/${SERVICENAME}/$CFILE" || die "Couldn't source ${ROOTPATH}/services/${SERVICENAME}/$CFILE"
