Better messages.

diff --git a/support/drunner-install-service b/support/drunner-install-service
--- a/support/drunner-install-service
+++ b/support/drunner-install-service
@@ -3,10 +3,11 @@
 
 #------------------------------------------------------------------------------------
 
-# loadService
+# loadService [NUKEOK]
 function loadService {
+   NUKEOK=${1:-""}   
    if [ ! -v SERVICENAME ] || [ -z "$SERVICENAME" ]; then die "loadService - SERVICENAME not defined." ; fi
-   bash "${ROOTPATH}/support/validator-service" "$SERVICENAME"
+   bash "${ROOTPATH}/support/validator-service" "$SERVICENAME" "$NUKEOK"
    if [ $? -ne 0 ]; then exit 1 ; fi
 
    source "${ROOTPATH}/services/${SERVICENAME}/drunner/service.cfg"
@@ -64,6 +65,7 @@ function install_createVolumes {
 # recreateservice
 # called by both install and SERVICE update.
 function recreateservice {   
+   NUKEOK=${1:-""}
    # the directory that the container will update.
    if [ ! -v SERVICENAME ]; then die "SERVICENAME undefined." ; fi
    if [ -d "${ROOTPATH}/services/${SERVICENAME}" ]; then rm -r "${ROOTPATH}/services/${SERVICENAME}" ; fi
@@ -89,7 +91,7 @@ function recreateservice {
    chmod -R a-w "${ROOTPATH}/services/${SERVICENAME}/drunner"
    
    # create _variables file for the service to read.
-   loadService
+   loadService "NUKEOK"
    
    STR_DOCKERVOLS=""
    STR_DOCKEROPTS=""
@@ -150,24 +152,25 @@ function installservice {
    if [ -z "$SERVICENAME" ]; then die "install requires SERVICENAME." ; fi
 
    if [ -d "${ROOTPATH}/services/${SERVICENAME}" ]; then
-      echo "${SERVICENAME} is already installed at ${ROOTPATH}/services/${SERVICENAME}. Initialisation cancelled.">&2
-      echo "Try ${CODE_S}drunner ${SERVICENAME} update${CODE_E} instead.">&2
+      echo -e "${SERVICENAME} is already installed at ${ROOTPATH}/services/${SERVICENAME}. Initialisation cancelled.">&2
+      echo -e "Try ${CODE_S}drunner ${SERVICENAME} update${CODE_E} instead.">&2
       exit 1
    fi
+
+   (      
+      set -e
       
-   validate-image 
-   recreateservice
-   install_createlaunchscript
-   install_createVolumes
-      
-   # Finally run the install script in the service.         
-   bash "${ROOTPATH}/services/${SERVICENAME}/drunner/servicerunner" install
-   
-   # validate the installed service.
-   bash "${ROOTPATH}/support/validator-service" "${SERVICENAME}"
+      validate-image 
+      recreateservice "NUKEOK"
+      install_createlaunchscript
+      install_createVolumes
+         
+      # Finally run the install script in the service.         
+      bash "${ROOTPATH}/services/${SERVICENAME}/drunner/servicerunner" install
+   )
    if [ $? -ne 0 ]; then
       destroy
-      die "Installation failed. System returned to clean state."
+      die "Installation failed. ${CODE_E} System returned to clean state."
    fi
     
    # TODO: If we had errors then destroy everything!
diff --git a/support/validator-service b/support/validator-service
--- a/support/validator-service
+++ b/support/validator-service
@@ -17,10 +17,13 @@ function die {
    echo -e " ">&2
    echo -e "\e[31m\e[1mService broken. ${1}\e[0m">&2
    echo -e " ">&2
-   echo -e "You can try moving the folder aside (${ROOTPATH}/services/${SERVICENAME})">&2
-   echo -e "then installing with the same SERVICENAME and IMAGENAME. Data and configuration">&2
-   echo -e "should be preserved if you're coming from a stable release.">&2
-   echo -e " ">&2
+   
+   if [ -z $NUKEOK ]; then
+      echo -e "You can try moving the folder aside (${ROOTPATH}/services/${SERVICENAME})">&2
+      echo -e "then installing with the same SERVICENAME and IMAGENAME. Data and configuration">&2
+      echo -e "should be preserved if you're coming from a stable release.">&2
+      echo -e " ">&2
+   fi
    exit 1
 }
 
@@ -32,6 +35,7 @@ source "/etc/drunner/drunner.cfg"
 
 # Validate service is installed okay
 SERVICENAME=${1:-""}
+NUKEOK=${2:-""}
 
 if [ -z "SERVICENAME" ]; then 
    echo -e "Usage: ${CODE_S}validator-service SERVICENAME${CODE_E}">&2
