Using atom, fixed line endings and whitespace.

diff --git a/support/drunner b/support/drunner
--- a/support/drunner
+++ b/support/drunner
@@ -1,18 +1,18 @@
 #!/bin/bash
 set -o nounset
 
-#          88  88888888ba                                                                  
-#          88  88      "8b                                                                 
-#          88  88      ,8P                                                                 
-#  ,adPPYb,88  88aaaaaa8P'  88       88  8b,dPPYba,   8b,dPPYba,    ,adPPYba,  8b,dPPYba,  
-# a8"    `Y88  88""""88'    88       88  88P'   `"8a  88P'   `"8a  a8P_____88  88P'   "Y8  
-# 8b       88  88    `8b    88       88  88       88  88       88  8PP"""""""  88          
-# "8a,   ,d88  88     `8b   "8a,   ,a88  88       88  88       88  "8b,   ,aa  88          
-#  `"8bbdP"Y8  88      `8b   `"YbbdP'Y8  88       88  88       88   `"Ybbd8"'  88          
-#                                                                                                                                                                           
-#                                                                                                          
+#          88  88888888ba
+#          88  88      "8b
+#          88  88      ,8P
+#  ,adPPYb,88  88aaaaaa8P'  88       88  8b,dPPYba,   8b,dPPYba,    ,adPPYba,  8b,dPPYba,
+# a8"    `Y88  88""""88'    88       88  88P'   `"8a  88P'   `"8a  a8P_____88  88P'   "Y8
+# 8b       88  88    `8b    88       88  88       88  88       88  8PP"""""""  88
+# "8a,   ,d88  88     `8b   "8a,   ,a88  88       88  88       88  "8b,   ,aa  88
+#  `"8bbdP"Y8  88      `8b   `"YbbdP'Y8  88       88  88       88   `"Ybbd8"'  88
+#
+#
 #  manage docker containers in a simple and consistent way.
-#  
+#
 #  See:
 #    https://github.com/j842/drunner
 #
@@ -51,9 +51,9 @@ if [ "$(uname -rv | grep -c Debian)" -eq 0 ]; then die "Built for Debian only." 
 
 # showservices
 function showservices {
-   # list available services. 
+   # list available services.
    echo "AVAILABLE SERVICES"
-   find "$ROOTPATH/services" -maxdepth 1 -mindepth 1 -type d | while read SPATH; do 
+   find "$ROOTPATH/services" -maxdepth 1 -mindepth 1 -type d | while read SPATH; do
       if [ -e "${SPATH}/imagename.sh" ]; then
          source "${SPATH}/imagename.sh"
          printf "   %-15s - %-55s\n" "${SPATH##*/}" "$IMAGENAME"
@@ -82,16 +82,16 @@ VERSION
 
 LOCATION
    $ROOTPATH
-                       
+
 SYNOPSIS
    drunner clean
    drunner list
    drunner update
    drunner checkimage IMAGENAME
-   
+
    [PASS=?] drunner backup  SERVICENAME BACKUPFILE
-   [PASS=?] drunner restore BACKUPFILE  SERVICENAME  
-   
+   [PASS=?] drunner restore BACKUPFILE  SERVICENAME
+
    drunner install    IMAGENAME [SERVICENAME]
    drunner update     SERVICENAME
    drunner recover    SERVICENAME
@@ -99,20 +99,20 @@ SYNOPSIS
    drunner obliterate SERVICENAME
    drunner enter      SERVICENAME [ARGS]
    drunner status     SERVICENAME
-   
+
    SERVICENAME
    SERVICENAME COMMAND ARGS
-   
+
 DESCRIPTION
    Provides a standard way to manage and run containers supporting dr.
    Intended to be used both manually and via Ansible.
    See https://github.com/j842/drunner
-   
+
 EXIT CODE
    0   - success
    1   - error
    3   - no changes made
-   
+
 EOF
 }
 
@@ -136,8 +136,8 @@ function updatedr {
       # run it to update the installation.
       "${TEMPDIR}/drunner-install" "$ROOTPATH" || die "dRunner update failed (drunner-install script failed)"
    )
-   local RVAL=$? 
-   
+   local RVAL=$?
+
    # tidy up and exit (it's not safe to continue with the old script after updating dRunner like this)
    rm -rf "${TEMPDIR}"
    exit "$RVAL"
@@ -181,7 +181,7 @@ function processServiceCommands {
          updateservice || die "Update failed."
          alldone "Update complete."
          ;;
-                  
+
       backup)
          if [ "$#" -eq 2 ]; then
             setServiceName "$1" ; shift
@@ -191,14 +191,14 @@ function processServiceCommands {
             dieusage "[PASS=?] drunner backup SERVICENAME BACKUPFILE"
          fi
          ;;
-         
+
       enter)
          setServiceName "$1" ; shift
          SCRIPTTORUN="${ROOTPATH}/services/${SERVICENAME}/drunner/servicerunner"
          bash "${SCRIPTTORUN}" "enter" "$@" || die "Failed."
          alldone "Complete."
          ;;
-         
+
       # servicecmd SERVICENAME COMMAND
       servicecmd)
          [ $# -gt 0 ] || die "$DCOMMAND shouldn't be invoked manually."
@@ -207,20 +207,20 @@ function processServiceCommands {
          if [ "$#" -eq 0 ] || [ "$1" = "help" ]; then
             showservicehelp
             die "$DCOMMAND $SERVICENAME requires a subcommand."
-         elif elementIn "$1" "${RESERVEDWORDS[@]}"; then 
+         elif elementIn "$1" "${RESERVEDWORDS[@]}"; then
             die "$1 is a reserved word. Try ${CODE_S}drunner ${1} ${SERVICENAME}${CODE_E} instead."
          else
             SCRIPTTORUN="${ROOTPATH}/services/${SERVICENAME}/drunner/servicerunner"
             SUBCOMMAND="$1" ; shift
             [ -e "${SCRIPTTORUN}" ] || die "${SERVICENAME} is broken. Try ${CODE_S}drunner recover ${SERVICENAME}${CODE_E}"
-            "${SCRIPTTORUN}" "$SUBCOMMAND" "$@" || die "${SERVICENAME} $SUBCOMMAND $@ failed."
-            alldone "${SERVICENAME} $SUBCOMMAND $@ complete."
+            "${SCRIPTTORUN}" "$SUBCOMMAND" "$@" || die "${SERVICENAME} $SUBCOMMAND $* failed."
+            alldone "${SERVICENAME} $SUBCOMMAND $* complete."
          fi
          ;;
 
       *)
          die "Unknown command $1"
-   esac     
+   esac
 }
 
 
@@ -231,30 +231,30 @@ function processdRunnerCommands {
    # start with high level commands (clean, list, update), and commands on a service
    # that do not expect the service to be fully configured (install, restore, destroy)
    DCOMMAND="$1" ; shift
-   case "$DCOMMAND" in 
+   case "$DCOMMAND" in
       clean)
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock spotify/docker-gc
          alldone "Clean completed."
          ;;
-         
+
       list)
          showservices || die "Failed to show services."
          exit 0
          ;;
-         
+
       update)
          # if no args then update dr itself.
          [ "$#" -gt 0 ] || { updatedr || die "Failed to update dRunner." ; alldone "Update complete." ; }
          # otherwise fall through - we want to update a service not dr.
          ;;
-         
+
       checkimage)
          [ "$#" -eq 1 ] || dieusage "drunner checkimage IMAGENAME"
          IMAGENAME="$1" ; shift
          validate-image || die "Not valid."
          alldone "Valid."
          ;;
-                  
+
       install)
          if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
             dieusage "drunner install IMAGENAME [SERVICENAME]"
@@ -276,15 +276,15 @@ function processdRunnerCommands {
          restore "$BACKUPFILE" || die "Restore failed."
          alldone "Restore succeeded."
          ;;
-         
-      status) 
+
+      status)
          [ "$#" -eq 1 ] || dieusage "drunner status SERVICENAME"
          SERVICENAME="$1" ; shift
          [ -e "${ROOTPATH}/services/${SERVICENAME}" ] || die "${SERVICENAME} is not installed. If you need to recover, install it and any existing Docker volumes will be preserved."
          "${ROOTPATH}/support/validator-service" "$SERVICENAME" || die "Validation failed!"
          alldone "${SERVICENAME} is installed and okay."
          ;;
-         
+
       recover)
          if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
             dieusage "drunner recover SERVICENAME [IMAGENAME]"
@@ -296,11 +296,11 @@ function processdRunnerCommands {
          loadServiceSilent
          [ "$#" -eq 0 ] || { IMAGENAME="$1" ; shift ; }
          [ -n "$IMAGENAME" ] || die "${SERVICENAME} does not have an existing image definition. You need to use ${CODE_S}drunner recover SERVICENAME IMAGENAME${CODE_E}"
-         
-         installservice || die "Recover failed."      
+
+         installservice || die "Recover failed."
          alldone "Recover complete."
-         ;;         
-         
+         ;;
+
       uninstall)
          [ $# -eq 1 ] || dieusage "drunner uninstall SERVICENAME"
          SERVICENAME="$1"
@@ -313,12 +313,12 @@ function processdRunnerCommands {
          SERVICENAME="$1"
          obliterateService || die "${SERVICENAME} obliterated, but there were errors."
          alldone "${SERVICENAME} and its containers obliterated - all data destroyed."
-         ;;    
-         
+         ;;
+
       unittests)
          test-imageNameisDev
-         ;;    
-   esac  
+         ;;
+   esac
 }
 
 #------------------------------------------------------------------------------------
@@ -330,14 +330,14 @@ function processdRunnerCommands {
 # ██║ ╚═╝ ██║██║  ██║██║██║ ╚████║
 # ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝
 
-function main {                                
+function main {
 
    [ "$#" -gt 0 ] || { showusage ; showservices ; exit 0 ;}
-   
+
    # Process (clean, list, update, install, restore, destroy)
    # These ones don't require a valid service.
    processdRunnerCommands "$@"
-   
+
    # everything from now on is expected to be based on a valid service
    processServiceCommands "$@"
 }
