New framework

diff --git a/support/validator-service b/support/validator-service
--- a/support/validator-service
+++ b/support/validator-service
@@ -33,7 +33,7 @@ function die {
 readonly MYDIR=$( dirname "$(readlink -f "$0")" )
 if ! "${MYDIR}/validator-drunner" ; then exit 1 ; fi
 
-source "/etc/drunner/drunner.cfg"
+source "/etc/drunner/config.sh"
 
 # Validate service is installed okay
 SERVICENAME=${1:-""}
@@ -45,30 +45,21 @@ if [ -z "SERVICENAME" ]; then
    exit 1
 fi
 
-if [ ! -d "${ROOTPATH}/services/${SERVICENAME}" ]; then 
-   die "The service is not installed in ${ROOTPATH}/services/${SERVICENAME}."
-fi
-if [ ! -d "${ROOTPATH}/services/${SERVICENAME}/drunner" ]; then 
-   die "The service's scripts are not installed correctly."
-fi
+[ -d "${ROOTPATH}/services/${SERVICENAME}" ] || die "The service is not installed in ${ROOTPATH}/services/${SERVICENAME}."
+[ -d "${ROOTPATH}/services/${SERVICENAME}/drunner" ] || die "The service's scripts are not installed correctly."
 
 # Check mandatory files in image (global var IMAGENAME) before touching host. Is it a valid dr container?
 readonly REQDFILES=("drunner/servicerunner")
 for CFILE in "${REQDFILES[@]}"; do
-   if [ ! -e "${ROOTPATH}/services/${SERVICENAME}/$CFILE" ]; then
-      die "Required file not present: $CFILE"
-   fi
+   [ -e "${ROOTPATH}/services/${SERVICENAME}/$CFILE" ] || die "Required file not present: $CFILE"
 done
 
-readonly SOURCEFILES=("_imagename" "drunner/service.cfg" "drunner/_variables")
+readonly SOURCEFILES=("imagename.sh" "drunner/servicecfg.sh" "drunner/variables.sh")
 for CFILE in "${SOURCEFILES[@]}"; do
-   if [ ! -e "${ROOTPATH}/services/${SERVICENAME}/$CFILE" ]; then
-      die "Required file not present: $CFILE"
-   fi
-   source "${ROOTPATH}/services/${SERVICENAME}/$CFILE"
-   if [ $? -ne 0 ]; then die "Couldn't source ${ROOTPATH}/services/${SERVICENAME}/$CFILE"; fi
+   [ -e "${ROOTPATH}/services/${SERVICENAME}/$CFILE" ] || die "Required file not present: $CFILE"
+   source "${ROOTPATH}/services/${SERVICENAME}/$CFILE" || die "Couldn't source ${ROOTPATH}/services/${SERVICENAME}/$CFILE"
 done
 
-if [ ! -v IMAGENAME ]; then die "IMAGENAME wasn't set by _imagename."; fi
+[ -v IMAGENAME ] || die "IMAGENAME wasn't set by imagename.sh"
 
 exit 0
