Fix bugs in validator-drunner, and use better tests

diff --git a/support/validator-drunner b/support/validator-drunner
--- a/support/validator-drunner
+++ b/support/validator-drunner
@@ -30,19 +30,22 @@ function die {
 }
 
 # Validate drunner is installed okay
-if [ -e "/etc/drunner/drunner.cfg" ]; then die "You have an old installation of drunner. Try copying drunner.cfg to config.sh in /etc/drunner, then drunner update"
-if [ ! -e "/etc/drunner/config.sh" ]; then die "/etc/drunner/config.sh missing." ; fi
+[ ! -e "/etc/drunner/drunner.cfg" ] || die "You have an old installation of drunner. Try copying drunner.cfg to config.sh in /etc/drunner, then drunner update"
+[ -e "/etc/drunner/config.sh" ] || die "/etc/drunner/config.sh missing."
+
 source "/etc/drunner/config.sh"
-if [ ! -v ROOTPATH ]; then die "config.sh doesn't set ROOTPATH."; fi
-if [ ! -v PULLONUPDATE ]; then die "config.sh doesn't set PULLONUPDATE."; fi
-if [ ! -v SUPPORTIMAGE ]; then die "config.sh doesn't set SUPPORTIMAGE."; fi
-if [ ! -v DRUNNERINSTALLURL ]; then die "config.sh doesn't set DRUNNERINSTALLURL."; fi
-if [ ! -v DRUNNERINSTALLTIME ]; then die "config.sh doesn't set DRUNNERINSTALLTIME."; fi
 
-if [ ! -d "$ROOTPATH" ]; then die "$ROOTPATH doesn't exist."; fi
+[ -v ROOTPATH ]            || die "config.sh doesn't set ROOTPATH."
+[ -v PULLONUPDATE ]        || die "config.sh doesn't set PULLONUPDATE."
+[ -v SUPPORTIMAGE ]        || die "config.sh doesn't set SUPPORTIMAGE."
+[ -v DRUNNERINSTALLURL ]   || die "config.sh doesn't set DRUNNERINSTALLURL."
+[ -v DRUNNERINSTALLTIME ]  || die "config.sh doesn't set DRUNNERINSTALLTIME."
+[ -d "$ROOTPATH" ]         || die "$ROOTPATH doesn't exist."
 
-if [ ! -e "${ROOTPATH}/support/buildtime.sh" ]; then die "${ROOTPATH}/support/buildtime.sh is missing." ; fi
+[ -e "${ROOTPATH}/support/buildtime.sh" ] || die "${ROOTPATH}/support/buildtime.sh is missing."
+
 source "${ROOTPATH}/support/buildtime.sh"
-if [ ! -v SUPPORTBUILDTIME ]; then die "buildtime.sh doesn't set SUPPORTBUILDTIME." ; fi
+
+[ -v SUPPORTBUILDTIME ]    || die "buildtime.sh doesn't set SUPPORTBUILDTIME." 
 
 exit 0
