New scheme of many volumes

diff --git a/dr/dr b/dr/dr
--- a/dr/dr
+++ b/dr/dr
@@ -26,12 +26,9 @@ fi
 readonly DR_CFG_FILE="/etc/dr/dr.cfg"
 
 # Global constants.
-readonly SERVICECFGFILE="service.cfg"
-readonly SERVICEBINDIR="bin"
 readonly REQDFILES=("install" "destroy" "backup" "restore" "help" "enter")
 readonly COPYIMAGE="j842/dr-baseimage-alpine"
 
-readonly BACKUP_VOLZIP="config_volume_container.tar.7z"
 readonly BACKUP_MAIN="backup.tar.7z"
 
 #------------------------------------------------------------------------------------
@@ -52,14 +49,22 @@ function dieusage {
 
 #------------------------------------------------------------------------------------
 
+function volexists {
+  docker volume ls | grep "$1" > /dev/null
+}
+
+#------------------------------------------------------------------------------------
+
 function checkdir {
    if [ -z "$1" ]; then die "Installation broken. Config file ${DR_CFG_FILE} doesn't set $2."; fi
    if [ ! -d "$1" ]; then die "Installation broken. $2 is set to $1 but it doesn't exist."; fi
 }
 
+#------------------------------------------------------------------------------------
+
 function initglobals {
    # defines ROOTPATH, DRSERVICESPATH, SUPPORTIMAGE, DRBINPATH
-   . "${DR_CFG_FILE}"
+   source "${DR_CFG_FILE}"
    
    # Check basic directories are okay
    checkdir "${ROOTPATH}" "ROOTPATH"
@@ -83,9 +88,9 @@ function showservices {
    # list available services. 
    echo "AVAILABLE SERVICES"
    find "$DRSERVICESPATH" -maxdepth 1 -mindepth 1 -type d | while read SPATH; do 
-      if [ -e "${SPATH}/${SERVICECFGFILE}" ]; then
-         . "${SPATH}/${SERVICECFGFILE}"
-         serviceline "${SPATH##*/}" "$SERVICEIMAGENAME"
+      if [ -e "${SPATH}/bin/_variables" ]; then
+         source "${SPATH}/bin/_variables"
+         serviceline "${SPATH##*/}" "$IMAGENAME"
       else
          serviceline "${SPATH##*/}" "Broken service"
       fi
@@ -177,10 +182,41 @@ EOF
 
 #------------------------------------------------------------------------------------
 
+# create_variables - create the _variables file for the service's dr scripts.
+function create_variables { 
+   # create _variables file.
+   if [ ! -e "${SERVICEBINPATH}/volumes" ]; then die "Missing volumes file for $SERVICENAME" ; fi
+   source "${SERVICEBINPATH}/volumes"
+   if [ ! -e "${VOLUMES}" ]; then die "volumes file did not contain a volumes definition!" ; fi
+   DOCKERVOLS=( )
+   DOCKEROPTS=( )
+   for i in "${!VOLUMES[@]}"; do
+      DOCKERVOLS[$((i))]="dr-${SERVICENAME}-${VOLUMES[i]//[![:alnum:]]/}"
+      DOCKEROPTS[$((2*i))]="-v"
+      DOCKEROPTS[$((2*i+1))]="${DOCKERVOLS[i]}:${VOLUMES[i]}"
+   done
+   
+   local DATESTAMP="$(TZ=Pacific/Auckland date -u +"%a, %d %b %Y %X %z")"
+   printf -v STR_DOCKERVOLS "\"%s\" " "${DOCKERVOLS[@]}"
+   printf -v STR_DOCKEROPTS "\"%s\" " "${DOCKEROPTS[@]}"
+   printf -v STR_VOLUMES "\"%s\" " "${VOLUMES[@]}"
+   cat <<EOF >"${SERVICEVARIABLESPATH}"
+# Auto generated by Docker Runner
+# ${DATESTAMP}
+VOLUMES=($VOLUMES)
+DOCKERVOLS=($DOCKERVOLS)
+DOCKEROPTS=($DOCKEROPTS)
+SERVICENAME="${SERVICENAME}"
+IMAGENAME="${IMAGENAME}"
+INSTALLTIME="${DATESTAMP}"
+EOF
+}
+
+#------------------------------------------------------------------------------------
+
 # copydrfiles
 function copydrfiles {   
    # the directory that the container will update.
-   local SERVICEBINPATH="${SERVICEPATH}/${SERVICEBINDIR}"
    if [ -d "${SERVICEBINPATH}" ]; then rm -r "${SERVICEBINPATH}" ; fi
    mkdir -p "${SERVICEBINPATH}"
 
@@ -207,7 +243,7 @@ function copydrfiles {
 #------------------------------------------------------------------------------------
 
 # initdrservice
-function initSERVICEPATH {
+function createSERVICEPATH {
    # can only call when service ROOTPATH not present (for safety)
    if [ -d "${SERVICEPATH}" ]; then
       echo "A service is already installed at ${SERVICEPATH}. Initialisation cancelled.">&2
@@ -216,20 +252,11 @@ function initSERVICEPATH {
    fi
 
    copydrfiles
-
-   # add standard dr config stuff.
-   local DATESTAMP="$(LC_ALL=C date -u +"%a, %d %b %Y %X %z")"
-   
-   cat <<EOF >"${SERVICECFGPATH}"
-# Docker Runner configuration file for ${SERVICENAME} - ${IMAGENAME}
-# Last modified ${DATESTAMP}
-
-SERVICEIMAGENAME=${IMAGENAME}
-EOF
+   create_variables
 
    # Check mandatory files made it over to host okay from the container.
    for HFILE in "${REQDFILES[@]}"; do
-      if [ ! -e "${SERVICEPATH}/${SERVICEBINDIR}/${HFILE}" ]; then 
+      if [ ! -e "${SERVICEBINPATH}/${HFILE}" ]; then 
          echo "Install failed - ${HFILE} is required but wasn't copied from image ${IMAGE}." 
          rm -r "${SERVICEPATH}"
          exit 1
@@ -240,7 +267,7 @@ EOF
 #------------------------------------------------------------------------------------
 
 # install
-# global variables ready: ROOTPATH, DRSERVICESPATH, SUPPORTIMAGE, SERVICENAME, SERVICEPATH, SERVICECFGPATH, IMAGENAME
+# global variables ready: ROOTPATH, DRSERVICESPATH, SUPPORTIMAGE, SERVICENAME, SERVICEPATH, SERVICEVARIABLESPATH, IMAGENAME
 function install {   
    if [ -z "$IMAGENAME" ]; then echo "dr install requires IMAGENAME.">&2 ; exit 1 ; fi
    if [ -z "$SERVICENAME" ]; then echo "dr install requires SERVICENAME.">&2 ; exit 1 ; fi
@@ -249,8 +276,7 @@ function install {
    
    local DNAME="dr-install"
 
-   # --- all four globals have been set.
-   initSERVICEPATH
+   createSERVICEPATH
    
    # create the standard config volume container.
    docker volume create --name="dr-${SERVICENAME}-config" >/dev/null
@@ -261,7 +287,7 @@ function install {
     
    # Run the install script, e.g. to create volume containers.
    # todo: tidy up return/exit codes!         
-   bash "${SERVICEPATH}/${SERVICEBINDIR}/install" "${SERVICENAME}" "${IMAGENAME}"
+   bash "${SERVICEBINPATH}/install" "${SERVICENAME}" "${IMAGENAME}"
    
    # allow direct execution of SERVICENAME without typing dr
    createlaunchscript
@@ -293,38 +319,30 @@ function update {
 #------------------------------------------------------------------------------------
 
 # destroy
-# global variables ready: ROOTPATH, DRSERVICESPATH, SUPPORTIMAGE, SERVICENAME, SERVICEPATH, SERVICECFGPATH, IMAGENAME
+# global variables ready: ROOTPATH, DRSERVICESPATH, SUPPORTIMAGE, SERVICENAME, SERVICEPATH, SERVICEVARIABLESPATH, IMAGENAME
 function destroy {
    if [ -z "$SERVICENAME" ]; then die "dr destroy requires SERVICENAME to be set." ; fi
    if [ ! -d "$SERVICEPATH" ]; then echo "The service ${SERVICENAME} does not exist.">&2 ; showservices ; exit 1 ; fi
    
-   local RVALD=0
-
-   # if the install process created a destroy script then run it, e.g. to destroy volume containers.
-   # todo: tidy up return/exit codes!         
-   if [ -e "${SERVICEPATH}/${SERVICEBINDIR}/destroy" ]; then
-      bash "${SERVICEPATH}/${SERVICEBINDIR}/destroy" "${SERVICENAME}" "${IMAGENAME}"
-   else 
-      echo "Missing destroy script: ${SERVICEPATH}/${SERVICEBINDIR}/destroy" >&2
-      RVALD=1
-   fi      
+   # call destroy in service.
+   if [ -e "${SERVICEBINPATH}/destroy" ]; then bash "${SERVICEBINPATH}/destroy" ; fi
    
    # remove volume container.
-   docker volume rm "dr-${SERVICENAME}-config" >/dev/null
+   for VOLNAME in "${DOCKERVOLS[@]}"; do      
+      docker volume rm "$VOLNAME" >/dev/null
+   done
    
    # remove launch script
    if [ -e "/usr/local/bin/${SERVICENAME}" ]; then rm "/usr/local/bin/${SERVICENAME}" ; fi
    
-   # clean up service directoy.
+   # delete service directoy.
    rm -r "${SERVICEPATH}"
-   
-   exit $RVALD
 }
 
 #------------------------------------------------------------------------------------
 
 # backup BACKUPFILE
-# global variables ready: ROOTPATH, DRSERVICESPATH, SUPPORTIMAGE, SERVICENAME, SERVICEPATH, SERVICECFGPATH, IMAGENAME
+# global variables ready: ROOTPATH, DRSERVICESPATH, SUPPORTIMAGE, SERVICENAME, SERVICEPATH, SERVICEVARIABLESPATH, IMAGENAME
 function backup {
    if [ -z "$1" ]; then die "No BACKUPFILE was specified." ; fi
    local BACKUPFILE=$(realpath "$1" | tr -d '\r\n')
@@ -342,18 +360,23 @@ function backup {
       local TEMPC="${TEMPPARENT}/containerbackup"
       mkdir -p "$TEMPC"
       
-      # back up the service config (SERVICECFGFILE) to the tempparent folder
-      cp "$SERVICECFGPATH" "$TEMPPARENT"
-         
-      # back up our volume container (dr-${SERVICENAME}-config).
-      "${SUPPORTPATH}/compress" "dr-${SERVICENAME}-config" "${TEMPF}" "${BACKUP_VOLZIP}"
-      
+      # back up the service variables (SERVICEVARIABLESPATH) to the tempparent folder
+      cp "$SERVICEVARIABLESPATH" "$TEMPPARENT"
+
       # call through to container to backup anything there in a subfolder.
+      # important this is called before backing up any volume containers, as
+      # it might put stuff in them.
       getUSERID
       chown "${USERID}" "${TEMPC}"
-      SCRIPTTORUN="${SERVICEPATH}/${SERVICEBINDIR}/backup"
-      bash "$SCRIPTTORUN" "$SERVICENAME" "$IMAGENAME" "$TEMPC"
-         
+      bash "${SERVICEBINPATH}/backup" "$TEMPC"
+                  
+      # back up our volume containers
+      for VOLNAME in "${DOCKERVOLS[@]}"; do      
+         volexists "$VOLNAME"
+         if [ $? -ne 0 ]; then die "A docker volume required for the backup was missing: $VOLNAME"; fi
+         "${SUPPORTPATH}/compress" "$VOLNAME" "${TEMPF}" "${VOLNAME}.tar.7z"
+      done      
+      
       # Compress everything with password
       "${SUPPORTPATH}/compress" "$TEMPPARENT" "$TEMPROOT" "${BACKUP_MAIN}"
       mv "${TEMPROOT}/${BACKUP_MAIN}" "$BACKUPFILE"
@@ -391,69 +414,43 @@ function restore {
       "${SUPPORTPATH}/decompress" "$TEMPPARENT" "$TEMPROOT" "$BACKUP_MAIN"
          
       # check backup has key files.
-      local KEYFILES=("${TEMPF}/${BACKUP_VOLZIP}" "${TEMPPARENT}/${SERVICECFGFILE}" "${TEMPC}")
-      for NEEDEDFILE in "${KEYFILES[@]}"; do
-         if [ ! -e "$NEEDEDFILE" ]; then die "Backup corrupt. Missing ${NEEDEDFILE}."; fi
+      if [ ! -e "$TEMPC" ]; then die "Backup corrupt. Missing ${TEMPC}."; fi
+      for NEEDEDFILE in "${DOCKERVOLS[@]}"; do
+         if [ ! -e "${NEEDEDFILE}.tar.7z" ]; then die "Backup corrupt. Missing backup file for docker volume ${NEEDEDFILE}."; fi
       done
       
       # set IMAGENAME - the only missing global var.
-      . "${TEMPPARENT}/${SERVICECFGFILE}"
-      IMAGENAME="$SERVICEIMAGENAME"
+      . "${TEMPPARENT}/_variables"
 
       # now can install base service
       install
          
-      # restore our volume container (dr-${SERVICENAME}-config), first destroying the one install just created.
-      "${SUPPORTPATH}/decompress" "dr-${SERVICENAME}-config" "${TEMPF}" "${BACKUP_VOLZIP}"
+      # restore volumes.
+      for VOLNAME in "${DOCKERVOLS[@]}"; do      
+         "${SUPPORTPATH}/decompress" "$VOLNAME" "${TEMPF}" "${VOLNAME}.tar.7z"
+      done
 
-      # We restore our backed up configuration, first removing the one install just created.
-      rm -f "${SERVICECFGPATH}"
-      cp "${TEMPPARENT}/${SERVICECFGFILE}" "$SERVICECFGPATH" 
+      # We restore our backed up _variables.
+      cp "${TEMPPARENT}/_variables" "$SERVICEVARIABLESPATH" 
       
-      # call through to container to restore its backup in TEMPC.
-      SCRIPTTORUN="${SERVICEPATH}/${SERVICEBINDIR}/restore"
-      bash "$SCRIPTTORUN" "$SERVICENAME" "$IMAGENAME" "$TEMPC"
+      # call through to container to restore its backup in TEMPC. Imporant this is the last step,
+      # so it can use any docker volumes, the _variables file etc.
+      bash "${SERVICEBINPATH}/restore" "$TEMPC"
    )
    RVAL="$?"
    rm -r "${TEMPROOT}"   
    if [ $RVAL -ne 0 ]; then die "Restore failed. Temp files have been removed." ; fi
       
    echo "The backup ${BACKUPFILE##*/} has been restored to ${SERVICENAME}."
+   
+   # our globals haven't been updated outside the subshell (IMAGENAME not set for example) so exit to be safe.
+   exit 0
 }
 
 #------------------------------------------------------------------------------------
-
-
-# retriveROOTPATH
-function retrieveROOTPATH {
-   DIRERR="Run   dr configure ROOTPATH   before any other commands."
-   if [ ! -d "$DRETCDIR" ]; then die "$DIRERR"; fi
-   ROOTPATH=$(<"${CFG_ROOTPATH}")
-   if [ -z "$ROOTPATH" ]; then die "$DIRERR"; fi
-   if [ ! -d "$ROOTPATH" ]; then die "$DIRERR"; fi
-}
-
-#------------------------------------------------------------------------------------
-
-# setglobals
-function setglobals {
-   # expects SERVICENAME to be set.
-   if [ -z "${SERVICENAME}" ]; then 
-      die "SERVICENAME has not been set." 
-   fi
-   retrieveROOTPATH
-
-   SERVICEPATH="${ROOTPATH}/${SERVICENAME}"
-   if [ ! -d "$SERVICEPATH" ]; then echo "The service ${SERVICENAME} does not exist.">&2 ; showservices ; exit 1 ; fi
-
-   if [ ! -e "${SERVICEPATH}/${CFG_IMAGENAME}" ]; then die "Error - ${CFG_IMAGENAME} doesn't exist."; fi
-   IMAGENAME=$(<"${SERVICEPATH}/${CFG_IMAGENAME}")
-   if [ -z "$IMAGENAME" ]; then die "Error - ${CFG_IMAGENAME} is empty." ; fi
-}
-
 
 function showservicehelp {
-   local HELPSCRIPT="${SERVICEPATH}/${SERVICEBINDIR}/help"
+   local HELPSCRIPT="${SERVICEBINPATH}/help"
    if [ -e "${HELPSCRIPT}" ]; then
       . "$SERVICECFGPATH"
       bash "${HELPSCRIPT}" "${SERVICENAME}" "${SERVICEIMAGENAME}"
@@ -500,9 +497,10 @@ function main {
    fi     
 
    # all other commands have SERVICENAME as first argument.
-   SERVICENAME="$1"
-   SERVICEPATH="${DRSERVICESPATH}/${SERVICENAME}"
-   SERVICECFGPATH="${SERVICEPATH}/${SERVICECFGFILE}"
+   readonly SERVICENAME="$1"
+   readonly SERVICEPATH="${DRSERVICESPATH}/${SERVICENAME}"
+   readonly SERVICEBINPATH="${SERVICEPATH}/bin"
+   readonly SERVICEVARIABLESPATH="${SERVICEBINPATH}/_variables"
 
    # dr SERVICE with no other params.
    if [ "$#" -eq 1 ]; then
@@ -542,9 +540,8 @@ function main {
    # If we've reached here then SERVICENAME is expected to exist. 
    # Read in SERVICEIMAGENAME from config file. 
    if [ ! -d "$SERVICEPATH" ]; then showservices ; die "Service $SERVICENAME does not exist." ; fi
-   if [ ! -e "$SERVICECFGPATH" ]; then die "Service ${SERVICENAME} is corrupt (missing its configuration file)." ; fi
-   . "$SERVICECFGPATH"
-   IMAGENAME="$SERVICEIMAGENAME"
+   if [ ! -e "$SERVICEVARIABLESPATH" ]; then die "Service ${SERVICENAME} is corrupt (missing its _variables file)." ; fi
+   source "$SERVICEVARIABLESPATH"
 
    # HANDLE COMMANDS FOR AN EXISTING SERVICE
    case "$USERCOMMAND" in
@@ -565,7 +562,7 @@ function main {
          ;;
 
       *)         
-         SCRIPTTORUN="${SERVICEPATH}/${SERVICEBINDIR}/${USERCOMMAND}"
+         SCRIPTTORUN="${SERVICEBINPATH}/${USERCOMMAND}"
          if [ -e "${SCRIPTTORUN}" ]; then
             bash "${SCRIPTTORUN}" "${SERVICENAME}" "${IMAGENAME}" "$@"
          else
