Fix major big in SERVICE update - it clobbered the _variables file.

diff --git a/dr/dr b/dr/dr
--- a/dr/dr
+++ b/dr/dr
@@ -225,66 +225,6 @@ EOF
 
 #------------------------------------------------------------------------------------
 
-# install_create_variables - create the _variables file for the service's dr scripts.
-function install_create_variables { 
-   # create _variables file.
-   if [ ! -e "${SERVICEBINPATH}/volumes" ]; then die "Missing volumes file for $SERVICENAME" ; fi
-   source "${SERVICEBINPATH}/volumes"
-   if [ ! -v VOLUMES ]; then die "volumes file did not contain a volumes definition!" ; fi
-   DOCKERVOLS=( )
-   DOCKEROPTS=( )
-   for i in "${!VOLUMES[@]}"; do
-      DOCKERVOLS[$((i))]="dr-${SERVICENAME}-${VOLUMES[i]//[![:alnum:]]/}"
-      DOCKEROPTS[$((2*i))]="-v"
-      DOCKEROPTS[$((2*i+1))]="${DOCKERVOLS[i]}:${VOLUMES[i]}"
-   done
-   
-   local DATESTAMP="$(TZ=Pacific/Auckland date -u +"%a, %d %b %Y %X %z")"
-   printf -v STR_DOCKERVOLS "\"%s\" " "${DOCKERVOLS[@]}"
-   printf -v STR_DOCKEROPTS "\"%s\" " "${DOCKEROPTS[@]}"
-   printf -v STR_VOLUMES "\"%s\" " "${VOLUMES[@]}"
-   cat <<EOF >"${SERVICEVARIABLESPATH}"
-# Auto generated by Docker Runner
-# ${DATESTAMP}
-VOLUMES=($VOLUMES)
-DOCKERVOLS=($DOCKERVOLS)
-DOCKEROPTS=($DOCKEROPTS)
-SERVICENAME="${SERVICENAME}"
-IMAGENAME="${IMAGENAME}"
-INSTALLTIME="${DATESTAMP}"
-EOF
-}
-
-#------------------------------------------------------------------------------------
-
-# install_copydrfiles
-function install_copydrfiles {   
-   # the directory that the container will update.
-   if [ -d "${SERVICEBINPATH}" ]; then rm -r "${SERVICEBINPATH}" ; fi
-   mkdir -p "${SERVICEBINPATH}"
-
-   # we need the user id for the account that the image uses.
-   getUSERID
-   if [ -z "$USERID" ] || [ "${USERID}" -eq 0 ]; then die "Internal error - USERID for image is not a normal user." ; fi
-
-   # allow the container to write into this folder.
-   chown "${USERID}" "${SERVICEBINPATH}"
-   
-   # assumes docker image does not use entrypoint. Could instead override entrypoint maybe.
-   docker run --rm -it -v "${SERVICEBINPATH}:/tempcopy" "${IMAGENAME}" /bin/bash -c "cp -r /dr/* /tempcopy/"                             
-   if [ $? -ne 0 ]; then 
-      echo "Failed to copy files.">&2 
-      echo "You will need to reinstall the service.">&2
-      rm -r "${SERVICEPATH}"
-      exit 1
-   fi  
-   # tighten up permissions
-   chown -R root:root "${SERVICEBINPATH}"
-   chmod -R a-w "${SERVICEBINPATH}"
-}
-
-#------------------------------------------------------------------------------------
-
 # install_checkReqdFiles
 function install_checkReqdFiles {
    # Check mandatory files made it over to host okay from the container.
@@ -316,6 +256,64 @@ function install_createVolumes {
       fi
    done     
 }
+
+
+#------------------------------------------------------------------------------------
+
+# recreateServiceBinPath
+# called by both install and SERVICE update.
+function recreateServiceBinPath {   
+   # the directory that the container will update.
+   if [ -d "${SERVICEBINPATH}" ]; then rm -r "${SERVICEBINPATH}" ; fi
+   mkdir -p "${SERVICEBINPATH}"
+
+   # we need the user id for the account that the image uses.
+   getUSERID
+   if [ -z "$USERID" ] || [ "${USERID}" -eq 0 ]; then die "Internal error - USERID for image is not a normal user." ; fi
+
+   # allow the container to write into this folder.
+   chown "${USERID}" "${SERVICEBINPATH}"
+   
+   # assumes docker image does not use entrypoint. Could instead override entrypoint maybe.
+   docker run --rm -it -v "${SERVICEBINPATH}:/tempcopy" "${IMAGENAME}" /bin/bash -c "cp -r /dr/* /tempcopy/"                             
+   if [ $? -ne 0 ]; then 
+      echo "Failed to copy files.">&2 
+      echo "You will need to reinstall the service.">&2
+      rm -r "${SERVICEPATH}"
+      exit 1
+   fi  
+   # tighten up permissions
+   chown -R root:root "${SERVICEBINPATH}"
+   chmod -R a-w "${SERVICEBINPATH}"
+   
+   # create _variables file.
+   if [ ! -e "${SERVICEBINPATH}/volumes" ]; then die "Missing volumes file for $SERVICENAME" ; fi
+   source "${SERVICEBINPATH}/volumes"
+   if [ ! -v VOLUMES ]; then die "volumes file did not contain a volumes definition!" ; fi
+   DOCKERVOLS=( )
+   DOCKEROPTS=( )
+   for i in "${!VOLUMES[@]}"; do
+      DOCKERVOLS[$((i))]="dr-${SERVICENAME}-${VOLUMES[i]//[![:alnum:]]/}"
+      DOCKEROPTS[$((2*i))]="-v"
+      DOCKEROPTS[$((2*i+1))]="${DOCKERVOLS[i]}:${VOLUMES[i]}"
+   done
+   
+   local DATESTAMP="$(TZ=Pacific/Auckland date -u +"%a, %d %b %Y %X %z")"
+   printf -v STR_DOCKERVOLS "\"%s\" " "${DOCKERVOLS[@]}"
+   printf -v STR_DOCKEROPTS "\"%s\" " "${DOCKEROPTS[@]}"
+   printf -v STR_VOLUMES "\"%s\" " "${VOLUMES[@]}"
+   cat <<EOF >"${SERVICEVARIABLESPATH}"
+# Auto generated by Docker Runner
+# ${DATESTAMP}
+VOLUMES=($VOLUMES)
+DOCKERVOLS=($DOCKERVOLS)
+DOCKEROPTS=($DOCKEROPTS)
+SERVICENAME="${SERVICENAME}"
+IMAGENAME="${IMAGENAME}"
+INSTALLTIME="${DATESTAMP}"
+EOF
+}
+
 #------------------------------------------------------------------------------------
 
 # install
@@ -334,8 +332,7 @@ function install {
      # set -e
       
       install_checkimage
-      install_copydrfiles
-      install_create_variables
+      recreateServiceBinPath
       install_checkReqdFiles
       install_createVolumes
       install_createlaunchscript
@@ -586,7 +583,7 @@ function main {
    # HANDLE COMMANDS FOR AN EXISTING SERVICE
    case "$USERCOMMAND" in
       update)
-         copydrfiles
+         recreateServiceBinPath
          ;;
                   
       backup)
