Ensure temporary files are removed on backup/restore (better security not leaving those around!)

diff --git a/dr/dr b/dr/dr
--- a/dr/dr
+++ b/dr/dr
@@ -332,27 +332,35 @@ function backup {
    if [ -e "$BACKUPFILE" ]; then die "$BACKUPFILE already exists. Aborting." ; fi
    
    local TEMPROOT="$(mktemp -d)"
-   local TEMPPARENT="${TEMPROOT}/backup"
-   local TEMPF="${TEMPPARENT}/drbackup"
-   mkdir -p "$TEMPF"
-   local TEMPC="${TEMPPARENT}/containerbackup"
-   mkdir -p "$TEMPC"
    
-   # back up the service config (SERVICECFGFILE) to the tempparent folder
-   cp "$SERVICECFGPATH" "$TEMPPARENT"
+   ( # SUBSHELL so we can tidy up easily if it goes wrong.
+      # bail if any command returns an error!
+      set -e
       
-   # back up our volume container (dr-${SERVICENAME}-config).
-   "${SUPPORTPATH}/compress" "dr-${SERVICENAME}-config" "${TEMPF}" "${BACKUP_VOLZIP}"
-   
-   # call through to container to backup anything there in a subfolder.
-   SCRIPTTORUN="${SERVICEPATH}/${SERVICEBINDIR}/backup"
-   bash "$SCRIPTTORUN" "$SERVICENAME" "$IMAGENAME" "$TEMPC"
+      local TEMPPARENT="${TEMPROOT}/backup"
+      local TEMPF="${TEMPPARENT}/drbackup"
+      mkdir -p "$TEMPF"
+      local TEMPC="${TEMPPARENT}/containerbackup"
+      mkdir -p "$TEMPC"
       
-   # Compress everything with password
-   "${SUPPORTPATH}/compress" "$TEMPPARENT" "$TEMPROOT" "${BACKUP_MAIN}"
-   mv "${TEMPROOT}/${BACKUP_MAIN}" "$BACKUPFILE"
-
+      # back up the service config (SERVICECFGFILE) to the tempparent folder
+      cp "$SERVICECFGPATH" "$TEMPPARENT"
+         
+      # back up our volume container (dr-${SERVICENAME}-config).
+      "${SUPPORTPATH}/compress" "dr-${SERVICENAME}-config" "${TEMPF}" "${BACKUP_VOLZIP}"
+      
+      # call through to container to backup anything there in a subfolder.
+      SCRIPTTORUN="${SERVICEPATH}/${SERVICEBINDIR}/backup"
+      bash "$SCRIPTTORUN" "$SERVICENAME" "$IMAGENAME" "$TEMPC"
+         
+      # Compress everything with password
+      "${SUPPORTPATH}/compress" "$TEMPPARENT" "$TEMPROOT" "${BACKUP_MAIN}"
+      mv "${TEMPROOT}/${BACKUP_MAIN}" "$BACKUPFILE"
+   )
+   RVAL="$?" 
    rm -r "${TEMPROOT}"
+   if [ $RVAL -ne 0 ]; then die "Backup failed. Temp files have been removed." ; fi
+   
    echo " ">&2
    echo "Backed up to $BACKUPFILE succesfully.">&2
 }
@@ -367,40 +375,49 @@ function restore {
    if [ -e "$SERVICEPATH" ]; then die "$SERVICENAME exists - destroy it before restoring from backup." ; fi
    
    local TEMPROOT="$(mktemp -d)"
-   local TEMPPARENT="${TEMPROOT}/backup"
-   local TEMPF="${TEMPPARENT}/drbackup"
-   mkdir -p "$TEMPF"
-   local TEMPC="${TEMPPARENT}/containerbackup"
-   mkdir -p "$TEMPC"
    
-   # decompress the main backup
-   cp "$BACKUPFILE" "${TEMPROOT}/${BACKUP_MAIN}"
-   "${SUPPORTPATH}/decompress" "$TEMPPARENT" "$TEMPROOT" "$BACKUP_MAIN"
+   ( # SUBSHELL so we can tidy up easily if it goes wrong.
+      # bail if any command returns an error!
+      set -e
+
+      local TEMPPARENT="${TEMPROOT}/backup"
+      local TEMPF="${TEMPPARENT}/drbackup"
+      mkdir -p "$TEMPF"
+      local TEMPC="${TEMPPARENT}/containerbackup"
+      mkdir -p "$TEMPC"
       
-   # check backup has key files.
-   local KEYFILES=("${TEMPF}/${BACKUP_VOLZIP}" "${TEMPPARENT}/${SERVICECFGFILE}")
-   for NEEDEDFILE in "${KEYFILES[@]}"; do
-      if [ ! -e "$NEEDEDFILE" ]; then die "Backup corrupt. Missing ${NEEDEDFILE}."; fi
-   done
-   
-   # set IMAGENAME - the only missing global var.
-   . "${TEMPPARENT}/${SERVICECFGFILE}"
-   IMAGENAME="$SERVICEIMAGENAME"
+      # decompress the main backup
+      cp "$BACKUPFILE" "${TEMPROOT}/${BACKUP_MAIN}"
+      "${SUPPORTPATH}/decompress" "$TEMPPARENT" "$TEMPROOT" "$BACKUP_MAIN"
+         
+      # check backup has key files.
+      local KEYFILES=("${TEMPF}/${BACKUP_VOLZIP}" "${TEMPPARENT}/${SERVICECFGFILE}")
+      for NEEDEDFILE in "${KEYFILES[@]}"; do
+         if [ ! -e "$NEEDEDFILE" ]; then die "Backup corrupt. Missing ${NEEDEDFILE}."; fi
+      done
+      
+      # set IMAGENAME - the only missing global var.
+      . "${TEMPPARENT}/${SERVICECFGFILE}"
+      IMAGENAME="$SERVICEIMAGENAME"
 
-   # now can install base service
-   install
-        
-   # restore our volume container (dr-${SERVICENAME}-config), first destroying the one install just created.
-   "${SUPPORTPATH}/decompress" "dr-${SERVICENAME}-config" "${TEMPF}" "${BACKUP_VOLZIP}"
+      # now can install base service
+      install
+         
+      # restore our volume container (dr-${SERVICENAME}-config), first destroying the one install just created.
+      "${SUPPORTPATH}/decompress" "dr-${SERVICENAME}-config" "${TEMPF}" "${BACKUP_VOLZIP}"
 
-   # We restore our backed up configuration, first removing the one install just created.
-   rm -f "${SERVICECFGPATH}"
-   cp "${TEMPPARENT}/${SERVICECFGFILE}" "$SERVICECFGPATH" 
-   
-   # call through to container to restore anything there.
-   SCRIPTTORUN="${SERVICEPATH}/${SERVICEBINDIR}/restore"
-   bash "$SCRIPTTORUN" "$SERVICENAME" "$IMAGENAME" "$TEMPC"
-   
+      # We restore our backed up configuration, first removing the one install just created.
+      rm -f "${SERVICECFGPATH}"
+      cp "${TEMPPARENT}/${SERVICECFGFILE}" "$SERVICECFGPATH" 
+      
+      # call through to container to restore anything there.
+      SCRIPTTORUN="${SERVICEPATH}/${SERVICEBINDIR}/restore"
+      bash "$SCRIPTTORUN" "$SERVICENAME" "$IMAGENAME" "$TEMPC"
+   )
+   RVAL="$?"
+   rm -r "${TEMPROOT}"   
+   if [ $RVAL -ne 0 ]; then die "Restore failed. Temp files have been removed." ; fi
+      
    echo "Service ${SERVICENAME} has been restored successfully."
 }
 
