Dynamic download of dr-install for update.

diff --git a/dr/dr b/dr/dr
--- a/dr/dr
+++ b/dr/dr
@@ -266,9 +266,21 @@ function install {
 #------------------------------------------------------------------------------------
 
 function update {
+   local TEMPDIR="$(mktemp -d)"
+   chmod a+rwx "${TEMPDIR}"
+   docker run -i -t --name="get-dr-install" -v "${TEMPDIR}:/tempdir" \
+               "${SUPPORTIMAGE}" get-dr-install "/tempdir"
+   local RVAL="$?"
+   docker rm "get-dr-install" >/dev/null 2>&1
+
+   if [ "$RVAL" -ne 0 ]; then die "Unable to get dr-install.">&2 ; fi
+   if [ ! -e "${TEMPDIR}/dr-install" ]; then die "dr-install mysteriously missing.">&2 ; fi
+   
    # dr-install is downloaded from GitHub and put in /dr/support/dr-install by the Dockerfile,
    # then copied to the host in ${SUPPORTPATH} by dr-install that's run by the user.
-   "${SUPPORTPATH}/dr-install" "${ROOTPATH}"
+   "${TEMPDIR}/dr-install" "${ROOTPATH}"
+   rm -r "${TEMPDIR}"
+   exit 0
 }
 
 #------------------------------------------------------------------------------------
