Empty array is the same as unset array :/

diff --git a/dr/dr b/dr/dr
--- a/dr/dr
+++ b/dr/dr
@@ -248,20 +248,23 @@ function install_createVolumes {
    local DNAME="dr-install-volcreate"
    local DVOL=""
    local DPATH=""
-   for i in "${!DOCKERVOLS[@]}"; do      
-      VOLNAME="${DOCKERVOLS[i]}"
-      VOLPATH="${VOLUMES[i]}"
+   
+   if [ -v VOLUMES ]; then
+      for i in "${!DOCKERVOLS[@]}"; do      
+         VOLNAME="${DOCKERVOLS[i]}"
+         VOLPATH="${VOLUMES[i]}"
 
-      if volexists "$VOLNAME" ; then 
-         echo "A docker volume already exists for: $VOLNAME. Reusing it.";
-      else
-         docker volume create --name="$DNAME" >/dev/null
-         # set permissions on config volume
-         docker run --name="$DNAME" -v "${VOLNAME}:${VOLPATH}" "${COPYIMAGE}" \
-            /bin/bash -c "chown ${USERID}:root ${VOLPATH} && date >> ${VOLPATH}/install_date"
-         docker rm "$DNAME" >/dev/null 
-      fi
-   done     
+         if volexists "$VOLNAME" ; then 
+            echo "A docker volume already exists for: $VOLNAME. Reusing it.";
+         else
+            docker volume create --name="$DNAME" >/dev/null
+            # set permissions on config volume
+            docker run --name="$DNAME" -v "${VOLNAME}:${VOLPATH}" "${COPYIMAGE}" \
+               /bin/bash -c "chown ${USERID}:root ${VOLPATH} && date >> ${VOLPATH}/install_date"
+            docker rm "$DNAME" >/dev/null 
+         fi
+      done     
+  fi
 }
 
 
@@ -296,21 +299,22 @@ function recreateServiceBinPath {
    # create _variables file.
    if [ ! -e "${SERVICEBINPATH}/${SERVICECFG}" ]; then die "Missing $SERVICECFG file for $SERVICENAME" ; fi
    if [ ! -v SERVICENAME ]; then die "SERVICENAME undefined." ; fi
+
    source "${SERVICEBINPATH}/${SERVICECFG}" "$SERVICENAME"
-   if [ ! -v VOLUMES ]; then die "$SERVICECFG file did not contain a VOLUMES definition!" ; fi
-   if [ ! -v CONTAINERS ]; then die "$SERVICECFG file did not contain a CONTAINERS definition!" ; fi
-   DOCKERVOLS=( )
-   DOCKEROPTS=( )
+   
    for i in "${!VOLUMES[@]}"; do
       DOCKERVOLS[$((i))]="dr-${SERVICENAME}-${VOLUMES[i]//[![:alnum:]]/}"
       DOCKEROPTS[$((2*i))]="-v"
       DOCKEROPTS[$((2*i+1))]="${DOCKERVOLS[i]}:${VOLUMES[i]}"
    done
+   STR_DOCKERVOLS=""
+   STR_DOCKEROPTS=""
+   STR_VOLUMES=""
    
    local DATESTAMP="$(TZ=Pacific/Auckland date -u +"%a, %d %b %Y %X %z")"
-   printf -v STR_DOCKERVOLS "\"%s\" " "${DOCKERVOLS[@]}"
-   printf -v STR_DOCKEROPTS "\"%s\" " "${DOCKEROPTS[@]}"
-   printf -v STR_VOLUMES "\"%s\" " "${VOLUMES[@]}"
+   if [ -v DOCKERVOLS ]; then printf -v STR_DOCKERVOLS "\"%s\" " "${DOCKERVOLS[@]}" ; fi
+   if [ -v DOCKEROPTS ]; then printf -v STR_DOCKEROPTS "\"%s\" " "${DOCKEROPTS[@]}" ; fi
+   if [ -v VOLUMES ]; then printf -v STR_VOLUMES "\"%s\" " "${VOLUMES[@]}" ; fi
    cat <<EOF >"${SERVICEVARIABLESPATH}"
 # Auto generated by Docker Runner
 # ${DATESTAMP}
@@ -398,7 +402,8 @@ function backup {
       mkdir -p "$TEMPC"
       
       # output variables needed for restore to the tempparent folder
-      printf -v STR_DOCKERVOLS "\"%s\" " "${DOCKERVOLS[@]}"
+      STR_DOCKERVOLS=""
+      if [ -v DOCKERVOLS ]; then printf -v STR_DOCKERVOLS "\"%s\" " "${DOCKERVOLS[@]}" ; fi
       cat <<EOF >"${TEMPPARENT}/_oldvariables"
 # Auto generated by Docker Runner
 OLDDOCKERVOLS=($STR_DOCKERVOLS)
@@ -413,12 +418,14 @@ EOF
       bash "${SERVICEBINPATH}/backup" "$TEMPC"
                   
       # back up our volume containers
-      for VOLNAME in "${DOCKERVOLS[@]}"; do      
-         volexists "$VOLNAME"
-         if [ $? -ne 0 ]; then die "A docker volume required for the backup was missing: $VOLNAME"; fi
-         "${SUPPORTPATH}/compress" "$VOLNAME" "${TEMPF}" "${VOLNAME}.tar.7z"
-         if [ ! -e "${TEMPF}/${VOLNAME}.tar.7z" ]; then die "Unable to back up ${VOLNAME}." ; fi
-      done      
+      if [ -v DOCKERVOLS ]; then
+         for VOLNAME in "${DOCKERVOLS[@]}"; do      
+            volexists "$VOLNAME"
+            if [ $? -ne 0 ]; then die "A docker volume required for the backup was missing: $VOLNAME"; fi
+            "${SUPPORTPATH}/compress" "$VOLNAME" "${TEMPF}" "${VOLNAME}.tar.7z"
+            if [ ! -e "${TEMPF}/${VOLNAME}.tar.7z" ]; then die "Unable to back up ${VOLNAME}." ; fi
+         done      
+      fi
       
       # Compress everything with password
       "${SUPPORTPATH}/compress" "$TEMPPARENT" "$TEMPROOT" "${BACKUP_MAIN}"
@@ -461,24 +468,28 @@ function restore {
          
       # check backup has key files.
       if [ ! -e "$TEMPC" ]; then die "Backup corrupt. Missing ${TEMPC}."; fi
-      for NEEDEDFILE in "${OLDDOCKERVOLS[@]}"; do
-         if [ ! -e "${TEMPF}/${NEEDEDFILE}.tar.7z" ]; then die "Backup corrupt. Missing backup file for docker volume ${NEEDEDFILE}."; fi
-      done
+      if [ -v OLDDOCKERVOLS ]; then
+         for NEEDEDFILE in "${OLDDOCKERVOLS[@]}"; do
+            if [ ! -e "${TEMPF}/${NEEDEDFILE}.tar.7z" ]; then die "Backup corrupt. Missing backup file for docker volume ${NEEDEDFILE}."; fi
+         done
+      fi
       
       # now can install base service. Updates DOCKERVOLS.
       install
          
       # restore volumes.
       # zip file names are based on the _old_ DOCKERVOLS, new volume name based on hte new ones.
-      if [ "${#OLDDOCKERVOLS[@]}" -gt "${#DOCKERVOLS[@]}" ]; then die "The number of volume containers the image requires has decreased. Not safe to restore." ; fi
-      if [ "${#OLDDOCKERVOLS[@]}" -lt "${#DOCKERVOLS[@]}" ]; then echo "The number of volume containers the image specifies has increased. We'll restore what we can, but this container might not work :/" ; fi
+      if [ -v OLDDOCKERVOLS ]; then
+         if [ "${#OLDDOCKERVOLS[@]}" -gt "${#DOCKERVOLS[@]}" ]; then die "The number of volume containers the image requires has decreased. Not safe to restore." ; fi
+         if [ "${#OLDDOCKERVOLS[@]}" -lt "${#DOCKERVOLS[@]}" ]; then echo "The number of volume containers the image specifies has increased. We'll restore what we can, but this container might not work :/" ; fi
 
-      for i in "${!OLDDOCKERVOLS[@]}"; do      
-         OLDVOLNAME="${OLDDOCKERVOLS[i]}"
-         NEWVOLNAME="${DOCKERVOLS[i]}"
-         
-         "${SUPPORTPATH}/decompress" "$NEWVOLNAME" "${TEMPF}" "${OLDVOLNAME}.tar.7z"
-      done
+         for i in "${!OLDDOCKERVOLS[@]}"; do      
+            OLDVOLNAME="${OLDDOCKERVOLS[i]}"
+            NEWVOLNAME="${DOCKERVOLS[i]}"
+            
+            "${SUPPORTPATH}/decompress" "$NEWVOLNAME" "${TEMPF}" "${OLDVOLNAME}.tar.7z"
+         done
+      fi
       
       # call through to container to restore its backup in TEMPC. Imporant this is the last step,
       # so it can use any docker volumes, the _variables file etc.
