Fixes now that we're not running as root.

diff --git a/support/run_on_service/validator-image b/support/run_on_service/validator-image
--- a/support/run_on_service/validator-image
+++ b/support/run_on_service/validator-image
@@ -31,7 +31,7 @@ for CFILE in "${REQDFILES[@]}"; do
    fi
 done
 
-source /drunner/servicecfg.sh
+source /drunner/servicecfg.sh || die "Couldn't load servicecfg.sh"
 
 exit 0
 
