Move 7z into container, to remove host requirement.

diff --git a/usrlocalbin/dr_compress b/usrlocalbin/dr_compress
--- a/usrlocalbin/dr_compress
+++ b/usrlocalbin/dr_compress
@@ -12,17 +12,15 @@ function die {
 }
 
 #------------------------------------------------------------------------------------
-# PASS=? dr_compress SOURCEFOLDER ARCHIVEFOLDER ARCHIVENAME
+# PASS=? dr_compress ARCHIVENAME
 
-if [ $# -ne 3 ]; then die "PASS=? dr_compress SOURCEFOLDER ARCHIVEFOLDER ARCHIVENAME" ; fi
+if [ "$#" -ne 1 ]; then die "PASS=? dr_compress ARCHIVENAME" ; fi
 
-SOURCEFOLDER=$(realpath "$1" | tr -d '\r\n')
-if [ $? -ne 0 ]; then die "dr_compress: Couldn't find source path ${1}." ; fi
+SOURCEFOLDER="/src"
+ARCHIVEPATH="/dst/$1"
 
-ARCHIVEFOLDER=$(realpath "$2" | tr -d '\r\n')
-if [ $? -ne 0 ]; then die "dr_compress: Couldn't find destination path ${2}." ; fi
-
-ARCHIVEPATH="$ARCHIVEFOLDER/$3"
+if [ -e $ARCHIVEPATH ]; then die "Archive $1 already exists. Aborting." fi
+if [ ! -d "$SOURCEFOLDER" ]; then die "dr_compress: Source folder does not exist: $SOURCEFOLDER"; fi
 
 # default to empty string if doesn't exist, then test for empty string.
 if [ -n "${PASS-}" ]; then 
@@ -33,5 +31,5 @@ else
 fi
 
 tar cf - -C "$SOURCEFOLDER" . | 7za a -si "${PASSCMD}" "$ARCHIVEPATH" > /dev/null
-if [ $? -ne 0 ]; then die "Failed to create archive of $SOURCEFOLDER" ; fi
+if [ $? -ne 0 ]; then die "Failed to create archive." ; fi
 
diff --git a/usrlocalbin/dr_decompress b/usrlocalbin/dr_decompress
--- a/usrlocalbin/dr_decompress
+++ b/usrlocalbin/dr_decompress
@@ -11,21 +11,24 @@ function die {
    exit 1
 }
 
-# PASS=? dr_decompress DESTFOLDER ARCHIVEFOLDER ARCHIVENAME
+#------------------------------------------------------------------------------------
+# PASS=? dr_decompress ARCHIVENAME
 
-if [ $# -ne 3 ]; then die "PASS=? dr_decompress DESTFOLDER ARCHIVEFOLDER ARCHIVENAME" ; fi
+if [ "$#" -ne 1 ]; then die "PASS=? dr_decompress ARCHIVENAME" ; fi
 
-DESTFOLDER=$(realpath "$1" | tr -d '\r\n')
-ARCHIVEFOLDER=$(realpath "$2" | tr -d '\r\n')
-ARCHIVEPATH="$ARCHIVEFOLDER/$3"
+DESTFOLDER="/dst"
+ARCHIVEPATH="/src/$3"
 
 if [ ! -e "$ARCHIVEPATH" ]; then die "dr_decompress: No such archive: $ARCHIVEPATH"; fi
 if [ ! -d "$DESTFOLDER" ]; then die "dr_decompress: Destination folder does not exist: $DESTFOLDER"; fi
  
-PASSCMD=""
+# default to empty string if doesn't exist, then test for empty string.
 if [ -n "${PASS-}" ]; then 
    PASSCMD="-p${PASS}"; 
+else
+   PASSCMD=""
+   echo "WARNING: No password supplied.">&2
 fi
 
 7za x -so "${PASSCMD}" "${ARCHIVEPATH}" | tar xf - -C "${DESTFOLDER}"
-if [ $? -ne 0 ]; then die "Failed to decompress archive $ARCHIVEPATH . The password may be incorrect!"; fi
+if [ $? -ne 0 ]; then die "Failed to decompress archive. The password may be incorrect!"; fi
